[web]
web-01 ansible_host=192.168.0.141 ansible_user=ubuntu backend_name=web-01
web-02 ansible_host=192.168.0.142 ansible_user=ubuntu backend_name=web-02

[lb]
lb-01 ansible_host=192.168.0.140 ansible_user=ubuntu keepalived_state=MASTER keepalived_priority=150

[ha_lab:children]
web
lb
